--Exercice 2

DELETE FROM AGENT_ENTRETIEN ;
DELETE FROM TRF_CHB ;
DELETE FROM PLANNING ;
DELETE FROM CHAMBRE ;
DELETE FROM TELEPHONE ;
DELETE FROM TYPE ;
DELETE FROM EMAIL ;
DELETE FROM LIGNE_FACTURE ;
DELETE FROM FACTURE ;
DELETE FROM MODE_PAIEMENT ;
DELETE FROM ADRESSE ;
DELETE FROM CLIENT ;
DELETE FROM TITRE ;







INSERT INTO titre (TIT_CODE ,
TIT_LIB)
SELECT TIT_CODE ,
TIT_LIB
FROM HOTEL.titre;


INSERT INTO type(TYP_CODE ,
TYP_LIB)
SELECT TYP_CODE ,
TYP_LIB 
FROM HOTEL.TYPE;


INSERT INTO client (CLI_ID,TIT_CODE,CLI_NOM,CLI_PRENOM,CLI_ENSEIGNE)
SELECT CLI_ID ,TIT_CODE ,CLI_NOM ,CLI_PRENOM ,CLI_ENSEIGNE  
FROM HOTEL.CLIENT;

INSERT INTO telephone (TEL_ID ,
CLI_ID ,
TYP_CODE ,
TEL_NUMERO ,
TEL_LOCALISATION)
SELECT TEL_ID ,
CLI_ID ,
TYP_CODE ,
TEL_NUMERO ,
TEL_LOCALISATION 
FROM HOTEL.TELEPHONE;


INSERT INTO email (EML_ID ,
CLI_ID ,
EML_ADRESSE ,
EML_LOCALISATION)
SELECT EML_ID ,
CLI_ID ,
EML_ADRESSE ,
EML_LOCALISATION 
FROM HOTEL.EMAIL;

INSERT INTO adresse (CLI_ID ,
ADR_ID ,
ADR_LIGNE1 ,
ADR_LIGNE2 ,
ADR_LIGNE3 ,
ADR_LIGNE4 ,
ADR_CP ,
ADR_VILLE )
SELECT CLI_ID ,
ADR_ID ,
ADR_LIGNE1 ,
ADR_LIGNE2 ,
ADR_LIGNE3 ,
ADR_LIGNE4 ,
ADR_CP ,
ADR_VILLE  
FROM HOTEL.ADRESSE;

INSERT INTO mode_paiement (PMT_CODE ,
PMT_LIB )
SELECT PMT_CODE ,
PMT_LIB 
FROM HOTEL.MODE_PAIEMENT;


INSERT INTO facture (FAC_ID ,
PMT_CODE ,
CLI_ID ,
ADR_ID ,
FAC_DATE ,
FAC_DAT_PMT )
SELECT FAC_ID ,
PMT_CODE ,
CLI_ID ,
ADR_ID ,
FAC_DATE ,
FAC_DAT_PMT 
FROM HOTEL.FACTURE
WHERE EXTRACT(YEAR FROM FAC_DATE) >= 2007;

INSERT INTO ligne_facture (LIF_ID ,
FAC_ID ,
QTE ,
REMISE_POURCENT ,
REMISE_MNT ,
MNT ,
TAUX_TVA )
SELECT l.LIF_ID ,
l.FAC_ID ,
l.QTE ,
l.REMISE_POURCENT ,
l.REMISE_MNT ,
l.MNT ,
l.TAUX_TVA 
FROM HOTEL.LIGNE_FACTURE l, HOTEL.FACTURE f
WHERE l.FAC_ID = f.FAC_ID
AND EXTRACT(YEAR FROM f.FAC_DATE) >= 2007;


INSERT INTO agent_entretien (AGT_ID ,
AGT_NOM ,
AGT_PRENOM ,
AGT_SX ,
AGT_DNAIS ,
AGT_EMB ,
AGT_DPT ,
AGT_SALAIRE )
SELECT AGT_ID ,
AGT_NOM ,
AGT_PRENOM ,
AGT_SX ,
AGT_DNAIS ,
AGT_EMB ,
AGT_DPT ,
AGT_SALAIRE 
FROM HOTEL.AGENT_ENTRETIEN;


INSERT INTO chambre (CHB_ID ,
CHB_COMMUNIQUE ,
CHB_NUMERO ,
CHB_ETAGE ,
CHB_BAIN ,
CHB_DOUCHE ,
CHB_WC ,
CHB_COUCHAGE ,
CHB_POSTE_TEL ,
AGT_ID )
SELECT CHB_ID ,
CHB_COMMUNIQUE ,
CHB_NUMERO ,
CHB_ETAGE ,
CHB_BAIN ,
CHB_DOUCHE ,
CHB_WC ,
CHB_COUCHAGE ,
CHB_POSTE_TEL ,
AGT_ID 
FROM HOTEL.CHAMBRE;


INSERT INTO trf_chb (CHB_ID ,
TRF_DATE_DEBUT ,
TRF_CHB_PRIX)
SELECT CHB_ID ,
TRF_DATE_DEBUT ,
TRF_CHB_PRIX 
FROM HOTEL.TRF_CHB
WHERE EXTRACT(YEAR FROM TRF_DATE_DEBUT) >= 2007;



INSERT INTO planning(CHB_ID ,
PLN_JOUR ,
CLI_ID ,
NB_PERS )
SELECT CHB_ID ,
PLN_JOUR ,
CLI_ID ,
NB_PERS 
FROM HOTEL.PLANNING
WHERE EXTRACT(YEAR FROM PLN_JOUR) >= 2007;